import os

LAST_DIR_FILE = os.path.join(os.path.expanduser("~"), ".gitbash6dir")
SCROLL_THRESHOLD = 5
CANVAS_HEIGHT = 130
SCROLLBAR_FILE_THRESHOLD = 7
FILESELECTION_SCROLL_THRESHOLD = 9
FILESELECTION_CANVAS_HEIGHT = 180
ENTRY_WIDTH_SHORT = 24
ENTRY_WIDTH_LONG = 38
